mod array_higher_functions;
mod bigint_methods;
mod builtins;
mod bytecode;
mod bytecode_decoder;
mod bytecode_stack_frame;
mod cat_stack_frame;
mod first_stack_frame;
mod helpers;
mod iteration;
mod native_frame_function;
mod native_function;
mod number_methods;
mod operations;
mod stack_frame;
mod string_methods;
mod todo_fn;
mod virtual_machine;
pub mod vs_array;
mod vs_class;
mod vs_function;
pub mod vs_object;
mod vs_symbol;
pub mod vs_value;

pub use bytecode::Bytecode;
pub use virtual_machine::VirtualMachine;
pub use vs_value::{LoadFunctionResult, ValTrait};
